SELECT * FROM TB_PEDIDO
SELECT * FROM TB_DETALHE_PEDIDO
SELECT * FROM TB_PRODUTO
SELECT * FROM TB_CLIENTE
SELECT * FROM TB_ENDERECO

-- QUAL PRODUTO TEVE MAIOR QUANTIDADE DE VENDAS NO MÊS 7 DE 1996 ?
SELECT PR.Descricao, SUM(DP.Quantidade) AS Quant_Vendas_Mes7_De_1996 FROM TB_PRODUTO PR
JOIN TB_DETALHE_PEDIDO DP ON PR.ProdutoId = DP.ProdutoId
JOIN TB_PEDIDO PE ON DP.NumeroPedido = PE.NumeroPedido
WHERE PE.DataPedido BETWEEN '1996-07-01' AND '1996-07-31'
GROUP BY PR.Descricao
ORDER BY SUM(DP.Quantidade) DESC

-- QUAL CLIENTE TEVE MAIOR GASTO NO MÊS 7 DE 1996 ?
SELECT C.NomeCompleto, SUM(DP.Preco) AS Cliente_Maior_Gasto FROM TB_CLIENTE C
JOIN TB_PEDIDO P ON C.ClienteId = P.ClienteId
JOIN TB_DETALHE_PEDIDO DP ON P.NumeroPedido = DP.NumeroPedido
WHERE P.DataPedido BETWEEN '1996-07-01' AND '1996-07-31'
GROUP BY C.NomeCompleto
ORDER BY SUM(DP.Preco) DESC

-- LISTA TODOS CLIENTES QUE MORAM NA ALEMANHA
SELECT C.NomeCompleto, E.Pais FROM TB_CLIENTE C
JOIN TB_ENDERECO E ON C.ClienteId = E.ClienteId
WHERE Pais = 'Alemanha'